name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build std
      run: cargo build --verbose
    - name: Build no-std
      run: cargo build --verbose --no-default-features
    - name: Test std
      run: cargo test --verbose
    - name: Test no-std
      run: cargo test --verbose --no-default-features
